#:schema node_modules/wrangler/config-schema.json
name = "toddle-worker-example"

main = "dist/index.js"
compatibility_date = "2025-02-05"

rules = [
  # Include all json files in the worker (should only be the actual project)
  { type = "Text", globs = ["**/*.json"], fallthrough = true }
]

[assets]
directory = "./assets"